version: '3.9'
services:
  app:
    build: 
      args: 
        user: ben
        uid: 1000
      context: ./ 
      dockerfile: Dockerfile 
    container_name: app-management
    expose:
      - 9000
    restart: unless-stopped
    volumes:
      - ./php.ini:/etc/php/8.0/cli/conf.d/php.ini
      - ./:/var/www
    networks:
      - management-net
    depends_on:
      - db

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx-management
    restart: unless-stopped
    ports:
      - 8004:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./:/var/www
    networks:
      - management-net
    depends_on:
      - app
      - db

  db:
    image: mariadb:10.9.3-jammy
    container_name: mysql-management
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_USER: "${DB_USERNAME:-secret}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    ports:
      - 3310:3306
    volumes:
      - management_data:/var/lib/mysql
    networks:
      - management-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  management-net:
    driver: bridge

volumes:
  management_data:
    driver: local
  
