version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 9000
    restart: unless-stopped
    environment:
      ROLE: app
      APPENV: ${APP_ENV:-production}
    volumes:
      - ./php.ini:/etc/php/8.1/cli/conf.d/php.ini
      - .:/var/www/html
    networks:
      - management-net
    depends_on:
      - mysql

  webserver:
    image: nginx:1.21.6-alpine
    ports:
      - 8004:80
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./:/var/www/html
    networks:
      - management-net
    depends_on:
      - app
      - mysql

  mysql:
    image: mariadb:10.9.3-jammy
    ports:
      - 3305:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_USER: "${DB_USERNAME:-secret}"
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - management-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  management-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local